### ISSUE TITLE
Stops and bike rental stations doesn't appear anymore on map

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#2256]
For some time (maybe a few months?) Digitransit doesn't display stops and bike rental stations on map anymore. They are still usable for routing and can be seen in Nearby list, but not visible on the map, even at maximum zoom.

**Comment by vesameskanen** [comment]
There was indeed a change in smoove bike rental handling. OTP api returns a new bike station attribute 'state' which in turn is read from smoove/style attribute. Digitransit UI draws bike stations based on the state value. Stations with unknown states are ignored. This is probably the reason to disappearance of bike rental stations.

Stops have not changed on the map as far as I know.

**Comment by kalon33** [comment]
@vesameskanen But that shouldn't affect GBFS feed, that should be displayed properly, should it?

For stops, are they still retrieved from OTP? Because I don't got them anymore on my DT instance for Paris, where I use to have them displayed. Same thing with terminals.

**Comment by vesameskanen** [comment]
This was my mistake, I did not  set appropriate default state for bike stations. Now fixed by:

https://github.com/HSLdevcom/OpenTripPlanner/pull/201

Regarding stops, still no idea. Can you send more information?

**Comment by kalon33** [comment]
@vesameskanen I can send you more information, but what do you need?

I don't have a dedicated stop map element for digitransit-ui as you may have, but stops used to be displayed on the map when zooming, and they are not displayed anymote

**Comment by kalon33** [comment]
@vesameskanen This still happen with latest OTP and DT master. I have stops and bike stations displayed in "Near you", but nothing on the map at maximum zoom. Does something changed in the configuration recently?

**Comment by vesameskanen** [comment]
Some quick thoughts:
- Icons got bigger and we had to update background map settings to prevent icon clipping at tile borders (background maps from the project hsl-map-server). Check out your map services, maybe the problem is there.
- Proxy (=ngingx) cache and cdn caused some delays in our service before updated map tiles appeared. Even the browser might cache invalid map tiles.

**Comment by kalon33** [comment]
@vesameskanen Should that also happen with my own instance?
I observe 404 errors as DT tries to retrieve that kind of files:
 https://transit.paris/9%20Avenue%20Du%20G%C3%A9n%C3%A9ral%20De%20Gaulle%2C%20Longjumeau%2C%20France%3A%3A48.694693%2C2.298091/-/16/33183/22589.pbf
(in CityBikes.js:44) 
https://transit.paris/9%20Avenue%20Du%20G%C3%A9n%C3%A9ral%20De%20Gaulle%2C%20Longjumeau%2C%20France%3A%3A48.694693%2C2.298091/-/16/33186/22592.pbf
(in Stops.js:41)

Is that linked? How can I provide that files?

**Comment by vesameskanen** [comment]
Sorry for delay in answering. Now I understand your problem better.

The current UI implementation sets a pretty heavy dependency on background map services. Instead of rendering all stops and bike stations retrieved from OTP, it draws only items currently visible in the background map.  So, drawing is primarily triggered by  vector tile information, and the details like real time state for visible items are queried from OTP.

To get this implementation working, you will need a similar sub service as we have in https://github.com/HSLdevcom/hsl-map-server . Setting that service up is far from being a trivial task, so another maybe more practical solution is to hook in an  alternative drawing approach where the data to be  drawn is requested directly from OTP.

**Comment by kalon33** [comment]
@vesameskanen Wasn't it the case before? Data drawn requested from OTP? Is there a simple way to get it back, or something planned on this side?
