### ISSUE TITLE
[regressions] New search bar is not working on Chrome for Android (LG G4), outputs only one result for stops on tablet interface...

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#978]
1) On Chrome under Android 6.0, nothing is displayed as search results when typing something, since PR #946 merging. 

2) On a Nexus 9 tablet, which has not the mobile interface but the desktop one, that works, except that stop research only displays one result, even if multiple stops have the same name, or contain the name searched as part of their full name (for example, typing "Luxembourg" in Paris returns only one Luxembourg stop (one of the bus ones, but neither the Luxembourg terminal, nor the train stop, nor "Musée du Luxembourg" stop).

On desktop interface, problem is the same as on mobile: no result.

3) BTW, on all interfaces, it is not possible to switch between "destination" and "route, stop or keyword" once something is typed.

**Comment by hannesj** [comment]
@kalon33 This should have been fixed now, can you confirm?

**Comment by kalon33** [comment]
@hannesj: 
Point 1. is still occurring.
On LG G4:
![screenshot_2016-11-17-22-04-44](https://cloud.githubusercontent.com/assets/460731/20407800/2d17e7da-ad13-11e6-890d-a96cae91525a.png)

On Nexus 9, where is works properly:
![screenshot_20161117-221202](https://cloud.githubusercontent.com/assets/460731/20407833/44f8421e-ad13-11e6-936b-7eb76431ca77.png)

Point 2. is fixed.
Point 3. is fixed too.
